#დიდი ასოთი რომ ჩაწერ მაგრამ საჭიროა პატარა ასო
#ეს არის სეის სესითივი
credits=1
CREDITS=1
#განსხავებაა ერთი აფერ ქეიში არის და მეორე ლოვერ ქეისში
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goaprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goaprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goaprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vvvvvprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)vprint goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)
# print goa)
# print goa)
# print goa)
# print goa)
# print goa)print goa)



